[build]
  # Build command for Netlify
  command = "npm run build:client"
  # Publish directory (where your built files are)
  publish = "dist/public"

[build.environment]
  # Ensure Netlify uses the correct Node version
  NODE_VERSION = "20"

# Redirect all routes to index.html for React Router compatibility
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"